name: Run script

on:
  schedule:
    - cron: '34 17 * * *'
  workflow_dispatch:

jobs:
  run:
    name: run-script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.6.14"
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Install the project
      run: uv sync
    - name: Setup playwright
      run: |
        uv run playwright install --with-deps webkit
    - name: Run script
      run: uv run pytest --browser=webkit search.py
    - name: Commit the update
      run: |
        git config --global user.email "chris.rowe@wri.org"
        git config --global user.name "Github Actions"
        git add irving_oil_prices.csv
        git commit -m "Github actions run"
        git push


