name: Run script

on:
  schedule:
    - cron: '34 17 * * *'
  workflow_dispatch:

jobs:
  run:
    name: run-script
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Setup playwright
      run: |
        playwright install-deps
        playwright install webkit
    - name: Run script
      run: pytest --browser=webkit search.py
    - name: Commit the update
      run: |
        git config --global user.email "chris.rowe@wri.org"
        git config --global user.name "Github Actions"
        git add irving_oil_prices.csv
        git commit -m "Github actions run"
        git push


