name: Run script

on:
  schedule:
    - cron: '51 17 * * 5'
  workflow_dispatch:

jobs:
  run:
    name: run-script
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install pytest
      run: |
        pip install pytest-playwright
        playwright install-deps
        playwright install
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: pytest search.py


